print ("ipl")
print ("hi")
print ("hello")
print ("how are you")
print ("goodbye")
print ("what to do next")
print ("what is your name")
print ("what is your age")
print ("what is your favorite color")
print ("what is your favorite food")
print ("what is your favorite movie")